name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install build-essential g++ make

    - name: Grant execute permission for build and test scripts
      run: |
        chmod +x ci/build.sh
        chmod +x ci/test.sh

    - name: Build binaries
      run: ./ci/build.sh

    - name: Run tests
      run: ./ci/test.sh

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ci/test_output.txt

    - name: Archive binaries
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: build/
