name: Build and Test SW Project with Serial Port Emulation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y socat minicom

      - name: Set up virtual COM ports with socat
        run: |
          sudo socat PTY,link=/dev/ttyCOM3,raw,echo=0 PTY,link=/dev/ttyCOM4,raw,echo=0 &
          sleep 2
          ls -l /dev/ttyCOM*

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Run software with serial port emulation
        run: |
          sudo chmod 666 /dev/ttyCOM3 /dev/ttyCOM4
          ./build/my_project_executable /dev/ttyCOM3 &
          echo "Test message from CI" > /dev/ttyCOM4
          cat < /dev/ttyCOM3

      - name: Test project
        run: |
          ./build/test_executable
