name: Build and Test SW Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Boost
        run: |
          choco install boost-msvc-14.2 --version=1.82.0
          choco install boost-msvc-14.2 --version=1.82.0 --pre --force
          echo BOOST_ROOT=C:/tools/boost_1_82_0 >> $GITHUB_ENV
          echo BOOST_INCLUDEDIR=C:/tools/boost_1_82_0 >> $GITHUB_ENV
          echo BOOST_LIBRARYDIR=C:/tools/boost_1_82_0/lib64-msvc-14.2 >> $GITHUB_ENV

      - name: Set up Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install dependencies
        run: |
          vcpkg integrate install
          vcpkg install boost-asio boost-system

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -A x64 ..
          cmake --build . --config Release

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
