name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Grant execute permission for build and test scripts
      run: bash -c "chmod +x ci/build.sh ci/test.sh"

    - name: Build binaries
      run: bash ci/build.sh

    - name: Run tests
      run: bash ci/test.sh

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ci/test_output.txt

    - name: Archive binaries
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: build/
