name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install mingw
        choco install socat

    - name: Set up virtual serial ports using Socat
      run: |
        socat -d -d PTY,link=COM3,raw,echo=0 PTY,link=COM4,raw,echo=0 &

    - name: Build SW
      run: g++ -o build/SW_Task2.exe src/SW_Task2/SW_Task2/client.cpp -lws2_32

    - name: Run SW program
      run: |
        build\SW_Task2.exe &
        sleep 2

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ci/test_output.txt

    - name: Archive binaries
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: build/
